/**
 * Module status row construction extracted from runtime validator.
 */
import { RNG, mulberry32, setSeed, rng, pick, U, LZW } from '../../utils/index.js';
import {
  T, SP, RAD, SH, S,
  DIFF_SETTINGS, SAVE_VERSION, CAP_MATH, getSalaryCap,
  POS_DEF, RATING_LABELS, ALL_POSITIONS, OFF_POSITIONS, DEF_POSITIONS,
  OFF_SCHEMES, DEF_SCHEMES, OFF_PLANS, DEF_PLANS,
  SCHEME_COUNTERS, SCHEME_FX, SCHEME_FLAVOR, getSchemeFlavorLine,
  GAMEPLANS, GP_COUNTERS, HOME_FIELD_ADV, RIVALRY_NAMES,
  ARCHETYPES, ARCH_BOOST, COACH_TRAITS, ARCH_TRAIT_POOLS, CLIQUE_TYPES,
  KEYMAP, ACTION_KEYS, TAB_ORDER,
} from '../../config/index.js';
import {
  HALFTIME_V2,
  TRAINING_CAMP_986,
  FRANCHISE_TAG_986,
  COMP_PICKS_986,
  INCENTIVES_986,
  GM_REP_986,
  COACH_CAROUSEL_986,
  makeContract,
  calcCapHit,
  calcDeadMoney,
  restructureContract,
  CONTRACT_VALUE_TABLE_994,
  AGE_VALUE_CURVE_994,
  calcContractScore994,
  calcDeadCap994,
  calcFourthDownEV995,
  OWNER_ARCHETYPES,
  initOwner,
  updateOwnerApproval,
  getOwnerStatus,
  getPersonality,
  traitScalar,
  generatePersonality,
  PERS_ICONS,
  PERS_LABELS,
  getDominantTrait,
  getContractPersonalityEffects,
  chemistryMod,
  systemFitMod,
  updateSystemFit,
  resetSystemFit,
  TRAITS,
  TRAIT_FX,
  TRAIT_MILESTONES95,
  getPlayerTraits95,
  hasTrait95,
  assignTraits,
  checkTraitMilestones95,
  makePick,
  pickConditionText972,
  pickValue,
  draftContract,
  aucContract,
  SCHEME_FIT,
  calcSchemeFit,
  fitTierFromScore,
  getPlayerSide,
  calcPlayerIdentityFit,
  calcTeamFit,
  getSchemeMismatchWarnings,
  FIT_GROUP_DEFS,
  voidYearDeadCap,
  v36_capHit,
  v36_deadIfTraded,
  v36_tradeSavings,
  splitDeadCapCharge,
  calcTradeImpact,
  addVoidYears,
  getTradeValue,
  getTeamNeeds,
  getGMTradeThresholdMod,
  getGMFABias,
  getGMDraftBias,
  STARTER_COUNTS,
  SCOUT_COSTS86,
  SCOUT_POINT_BASE86,
  genPickBlurb,
  genRunAlerts,
  NARRATIVE_STATES,
  STORY_ARC_EVENTS,
  pickWeightedEvent,
  RIVALRY_TROPHIES_986,
  POWER_RANKINGS_986,
  CAP_PROJ_986,
  GENERATIONAL_986,
  OWNER_MODE_986,
  PLAYER_COMPARE_986,
  TIMELINE_986,
  CEREMONY_986,
  PRACTICE_SQUAD_986,
  HOLDOUT_V2_986,
  EXPANSION_DRAFT_986,
  SCOUT_SPEND_MENU95,
  SCOUT_MATH,
  SCOUT_NOTE_FLAVOR,
  getScoutNoteFlavor,
  UNLOCK_DEFS,
  DEFAULT_UNLOCKS,
  checkUnlocks,
  isTabUnlocked,
  SPECIAL_PLAYS_993,
  SPECIAL_COVERAGES_993,
  EP_TABLE_993,
  getEP993,
  LEVERAGE_INDEX_993,
  calcWinProbV2_993,
  PLAYBOOK_986,
  PRESS_CONF_986,
  LEGACY,
  RELOCATION_CITIES976,
  RELOCATION976,
  GM_STRATEGIES,
  applyGMStrategy,
  FO_TRAITS,
  FRONT_OFFICE,
  STORY_ARC_ENGINE,
  WEEKLY_CHALLENGES,
  TRADE_DEADLINE_FRENZY,
  TEAM_CLIMATES,
  CLIMATE_PROFILES,
  WEATHER,
  HT_CONDITIONS,
  HT_STRATEGIES,
  AGE_CURVES,
  PLAYER_ARCHETYPES,
  ARCHETYPE_AGING,
  COACH_SKILL_TREE,
  OWNER_PATIENCE,
  OWNER_CONFIDENCE_ARC,
  OWNER_CONSEQUENCES,
  TRADE_MATH,
  RECORDS_WALL,
  GM_TRADE_PITCH,
  getGMTradePitch,
  BREAKOUT_SYSTEM,
  GRUDGE_MATCH,
  REVENGE_GAME,
  MENTOR_SYSTEM,
  STAFF_POACHING,
  ALL_TIME_RECORDS,
  FILM,
  AGENT_TYPES,
  assignAgentType,
  getAgentTypeObj,
  TRUST_TREND,
  AGING_V2,
  TRUST,
  getPosMarketTier86,
  HOLDOUT_SYSTEM,
  calcFatigueMultiplier,
  calcGameScriptMult,
  calcWeekDeltas,
  attributeCause,
  AWARD_HISTORY_LOG,
  recordAwardHistory,
  getMultiTimeWinners,
  getTrophyName,
  setTrophyNameForRivalry,
  buildCareerPage,
  COACH_LEGACY_LOG,
  updateCoachLegacy,
  recordCoachRing,
  getCoachLegacyTop,
  buildDNAImpactReport,
  calcTradeValue,
  calcPickValue,
  evaluateTradePackage,
  RING_OF_HONOR_LOG,
  nominateForRing,
  autoRingOfHonor,
  getRingOfHonor,
  OWNER_PERSONALITY_EVENTS,
  checkOwnerPersonality,
  buildAwardsCeremony,
  buildCapVisualization,
  ROLE_DEFS,
  assignDefaultRoles,
  getRoleSnapPct,
  calcDominanceScore,
  calcDynastyIndex,
  calcPeakPower,
  calcLongevity,
  generateIdentityTags,
  ERA_THRESHOLD,
  generateEraCards,
  buildHallOfSeasons,
  rivalryKey,
  checkHateWeek,
  MOMENT_GRAVITY,
  addRivalryMoment,
  getBiggestMoment,
  MOMENT_CATEGORIES,
  categorizeMoment,
  buildRivalryTrophyCase,
  buildRivalryLadder,
  buildRivalryLadderLite,
  generateHighlights,
  generateReceipts,
  FIX_IT_DRILLS,
  PRACTICE_FOCUS,
  CAPTAIN_RULES,
  CAPTAIN_MOMENT_TYPES,
  PROSPECT_CLAIMS,
  CLINIC_TRACKS,
  CLINIC,
  CLINIC_MATH,
  MEDIA_TAGS,
  PRESS_TAG_MAP,
  getMediaPersona,
  CREDIBILITY_MATH,
  RIVALRY_MATH,
  PRESS_QUESTIONS,
  HEADLINES,
  HALL_OF_FAME_LOG,
  HOF_SPEECHES,
  getHOFSpeech,
  calcLegacyScore,
  autoHallOfFame,
  buildCapFixes,
  SCOUT,
  OC_SPECIALTIES,
  DC_SPECIALTIES,
  assignCoordSpecialty,
  PROSPECT_CHARACTER,
  BUST_STEAL_CALC,
  DRAFT_DAY_TRADES,
  DRAFT_EVAL,
  INJURY_REPORT,
  buildBracketTree,
  DOSSIER,
  SCOUT_REPORT,
  PROSPECT_DOSSIER,
  DRAFT_WAR_ROOM,
  OFFSEASON_EVENTS,
  OWNER_GOAL_TEMPLATES,
  COACH_GOAL_TEMPLATES,
  PLAYER_GOAL_TEMPLATES,
  generateSeasonGoals,
  generatePlayerGoals,
  updateGoalProgress,
  evaluateGoals,
  LOCKER_EVENTS,
  checkLockerEvents,
  getCoachTraitMods,
  OWNER_TYPES,
  OWNER_GOALS,
  STAT_HEADLINES,
  getStatHeadline,
  getTraitMoraleExplainer,
  STORY_TEMPLATES,
  PRESSER_TAG_TRIGGERS,
  gradeL,
  getFuzzyRating,
  getFuzzyGrade,
  OFFSEASON_NEWS,
  getRivalryLabel,
  findRivalObj,
  WP_TABLE_DEEPSEEK,
  momentumDecay991,
  edgeToProbability991,
  draftPickOvr991,
  aiPickOffGPPreview,
  aiPickDefGPPreview,
  RIVALRY_TROPHIES977,
  RIVALRY_WEEK977,
  PREGAME_TALK977,
  HALFTIME_PANEL977,
  POSTGAME_LOCKER977,
  GAME_OF_WEEK977,
  buildRivalryDashboard977,
  DB_CLEANER,
  detectPositionBattles974,
  buildCutAdvisor974,
  NEGOTIATION_SCENE,
  ARC_SPOTLIGHT,
} from '../../systems/index.js';
import {
  TD,
  LEAGUE_TEAM_COUNT97,
  REG_SEASON_WEEKS97,
  REG_SEASON_GAMES97,
  LEAGUE_POOL_SCALE97,
  MFD97_CONF_DIV_MAP,
  LEAGUE_STRUCTURE,
  applyLeagueAlignment97,
  getScaledCount97,
  CALENDAR,
  STADIUM_DEALS976,
  generateStadiumDeals976,
  TEAM_FLAVOR_991,
  getTeamFlavor991,
  LOCKER_ROOM_994,
  COACH_PLAYER_VOICE_994,
  PLAYOFF_NARRATIVE_993,
  COMEBACK_994,
  TRADE_DEADLINE_994,
  DYNASTY_MOMENTS_995,
  STADIUM_UPGRADE_995,
  CHAMPION_VOICE_995,
  POWER_RANKINGS_SHOW_995,
  COACH_PERSONALITIES_991,
  BROADCAST_COMMENTARY,
  BROADCAST_COMMENTARY_EXPANDED,
  MFSN_DRAFT_LINES,
  MFSN_SHOW,
  MFSN_CONTENT_991,
  MFSN_WEEKLY975,
  MFSN_BROADCAST,
  MFSN_DRAFT_GRADES,
  MFSN_PREDICTIONS,
  MFSN_EXPANDED_993,
  MFSN_SITUATIONAL_994,
  MFSN_FOURTH_DOWN_994,
  MFSN_DRIVES_994,
  SOCIAL_FEED_994,
  MFSN_OVERTIME_994,
  PLAYER_NAMES_991,
  SCOUTING_TEMPLATES_991,
  DRAFT_COMMENTARY,
  getDraftCommentary,
  DRAFT_ANALYST_993,
  RIVALRY_TRASH_991,
  COL_POWER,
  COL_G5,
  COL_FCS,
  COL_WEIGHTED,
  pickCollege,
  BROADCAST_VOICES_991,
  DRAFT_PRESSER975,
  HELP_SECTIONS,
  SKIN_TONES,
  HAIR_COLORS,
  FA_NARRATIVE_993,
  PRESS_CONFERENCE_993,
  FA_TIERS,
  getFATier,
  FA_PHASES,
  FA_ROLE_PITCH,
  RFA_TENDERS,
  FA_MARKET_VALUE,
  FA_PRIORITY_TAGS,
} from '../../data/index.js';


export function buildModuleStatusRows() {
  return [
    { name: 'RNG (mulberry32)', status: true },
    { name: 'Theme (T, SP, RAD, SH, S)', status: !!T.bg },
    { name: 'Difficulty Settings', status: !!DIFF_SETTINGS.rookie },
    { name: 'Cap Math', status: getSalaryCap(2026) === 255 },
    { name: 'Halftime Adjustments v2', status: HALFTIME_V2.options.length === 6 },
    { name: 'Training Camp', status: TRAINING_CAMP_986.focuses.length === 5 },
    { name: 'Franchise Tags', status: FRANCHISE_TAG_986.types.length === 3 },
    { name: 'Compensatory Picks', status: typeof COMP_PICKS_986.calculate === 'function' },
    { name: 'Contract Incentives', status: INCENTIVES_986.types.length === 7 },
    { name: 'GM Reputation', status: typeof GM_REP_986.calculate === 'function' },
    { name: 'Position Definitions (11 pos, 20 ratings each)', status: ALL_POSITIONS.length === 11 },
    { name: 'Rating Labels', status: !!RATING_LABELS.arm },
    { name: 'Offensive Schemes (8)', status: OFF_SCHEMES.length === 8 },
    { name: 'Defensive Schemes (5)', status: DEF_SCHEMES.length === 5 },
    { name: 'Game Plans (Off: 6, Def: 6)', status: OFF_PLANS.length === 6 && DEF_PLANS.length === 6 },
    { name: 'Scheme Counter Matrix', status: !!SCHEME_COUNTERS.air_raid },
    { name: 'Scheme FX & Flavor Text', status: !!SCHEME_FX.air_raid && !!SCHEME_FLAVOR.spread },
    { name: 'Coaching Archetypes (HC/OC/DC)', status: ARCHETYPES.HC.length === 3 },
    { name: 'Coach Traits (10 traits)', status: Object.keys(COACH_TRAITS).length === 10 },
    { name: 'Clique Types', status: CLIQUE_TYPES.length === 3 },
    { name: 'Owner Archetypes (5 types)', status: OWNER_ARCHETYPES.length === 5 },
    { name: 'Owner Approval System', status: typeof initOwner === 'function' },
    { name: 'Coach Carousel', status: typeof COACH_CAROUSEL_986.fireCoach === 'function' },
    { name: 'Contract System', status: typeof makeContract === 'function' },
    { name: 'Contract Scoring', status: typeof calcContractScore994 === 'function' },
    { name: 'Dead Cap Calculator', status: typeof calcDeadCap994 === 'function' },
    { name: '4th Down EV Calculator', status: typeof calcFourthDownEV995 === 'function' },
    { name: 'Personality System (5 axes)', status: typeof getPersonality === 'function' },
    { name: 'Personality Icons & Labels', status: !!PERS_ICONS.workEthic && !!PERS_LABELS.loyalty },
    { name: 'Dominant Trait Detection', status: typeof getDominantTrait === 'function' },
    { name: 'Contract Personality Effects', status: typeof getContractPersonalityEffects === 'function' },
    { name: 'Chemistry Modifier', status: typeof chemistryMod === 'function' },
    { name: 'System Fit Modifier', status: typeof systemFitMod === 'function' },
    { name: 'System Fit Growth/Reset', status: typeof updateSystemFit === 'function' && typeof resetSystemFit === 'function' },
    { name: 'Team Definitions (30 teams)', status: TD.length === 30 },
    { name: 'League Structure (2 conf, 6 div)', status: LEAGUE_STRUCTURE.conferences.length === 2 && LEAGUE_STRUCTURE.divisions.length === 6 },
    { name: 'Conference/Division Map', status: !!MFD97_CONF_DIV_MAP.hawks },
    { name: 'Season Calendar (16 events)', status: CALENDAR.length === 16 },
    { name: 'League Scaling Utilities', status: typeof getScaledCount97 === 'function' },
    { name: 'Player Traits (25 traits)', status: Object.keys(TRAITS).length === 25 },
    { name: 'Trait Effects (FX)', status: !!TRAIT_FX.clutch },
    { name: 'Trait Milestones (10 traits)', status: !!TRAIT_MILESTONES95.ironman },
    { name: 'Trait Detection (hasTrait95)', status: typeof hasTrait95 === 'function' },
    { name: 'Trait Assignment (up to 3)', status: typeof assignTraits === 'function' },
    { name: 'Draft Pick Creation', status: typeof makePick === 'function' },
    { name: 'Conditional Pick Logic', status: typeof pickConditionText972 === 'function' },
    { name: 'Pick Value Chart', status: pickValue(1) === 200 },
    { name: 'Draft Contracts', status: typeof draftContract === 'function' },
    { name: 'Auction Contracts', status: typeof aucContract === 'function' },
    { name: 'Scheme Fit Profiles (13 schemes)', status: Object.keys(SCHEME_FIT).length === 13 },
    { name: 'Scheme Fit Calculator', status: typeof calcSchemeFit === 'function' },
    { name: 'Player Identity Fit (composite)', status: typeof calcPlayerIdentityFit === 'function' },
    { name: 'Team Fit Aggregation', status: typeof calcTeamFit === 'function' },
    { name: 'Scheme Mismatch Warnings', status: typeof getSchemeMismatchWarnings === 'function' },
    { name: 'Fit Group Definitions', status: FIT_GROUP_DEFS.length === 7 },
    { name: 'Contract Cap Hit (v36)', status: typeof v36_capHit === 'function' },
    { name: 'Dead Cap & Trade Savings', status: typeof v36_deadIfTraded === 'function' },
    { name: 'Void Year Dead Cap', status: typeof voidYearDeadCap === 'function' },
    { name: 'Dead Cap Split (post-deadline)', status: typeof splitDeadCapCharge === 'function' },
    { name: 'Trade Impact Calculator', status: typeof calcTradeImpact === 'function' },
    { name: 'Void Year Management', status: typeof addVoidYears === 'function' },
    { name: 'Trade Value Calculator', status: typeof getTradeValue === 'function' },
    { name: 'Team Needs Analysis', status: typeof getTeamNeeds === 'function' },
    { name: 'GM Strategy Modifiers', status: typeof getGMTradeThresholdMod === 'function' },
    { name: 'GM FA & Draft Bias', status: typeof getGMFABias === 'function' && typeof getGMDraftBias === 'function' },
    { name: 'Starter Counts (11 pos)', status: STARTER_COUNTS.QB === 1 && STARTER_COUNTS.OL === 5 },
    { name: 'Scout Costs & Points', status: SCOUT_COSTS86.full === 100 },
    { name: 'Draft Blurb Generator', status: typeof genPickBlurb === 'function' },
    { name: 'Draft Run Alerts', status: typeof genRunAlerts === 'function' },
    { name: 'Narrative States (9 arcs)', status: Object.keys(NARRATIVE_STATES).length === 9 },
    { name: 'Story Arc Events', status: !!STORY_ARC_EVENTS.breakout },
    { name: 'Weighted Event Picker', status: typeof pickWeightedEvent === 'function' },
    { name: 'Stadium Deals (8 templates)', status: STADIUM_DEALS976.length === 8 },
    { name: 'Stadium Deal Generator', status: typeof generateStadiumDeals976 === 'function' },
    { name: 'Team Flavor (30 stadiums/fans)', status: Object.keys(TEAM_FLAVOR_991).length >= 28 },
    { name: 'Contract Value Tables (11 pos)', status: !!CONTRACT_VALUE_TABLE_994.QB },
    { name: 'Age Value Curves (11 pos)', status: !!AGE_VALUE_CURVE_994.QB },
    { name: 'Locker Room Narratives', status: !!LOCKER_ROOM_994.newArrival },
    { name: 'Coach-Player Voice (synergy/friction)', status: !!COACH_PLAYER_VOICE_994.synergy },
    { name: 'Playoff Narrative (9 categories)', status: !!PLAYOFF_NARRATIVE_993.clinchedBerth },
    { name: 'Comeback & Redemption Arcs', status: !!COMEBACK_994.injuryReturn },
    { name: 'Trade Deadline Narrative (7 categories)', status: !!TRADE_DEADLINE_994.deadlineFrenzy },
    { name: 'Dynasty Moments (6 event types)', status: !!DYNASTY_MOMENTS_995.firstChampionship },
    { name: 'Stadium Upgrade Narrative', status: !!STADIUM_UPGRADE_995.newStadiumOpen },
    { name: 'Champion Voice (6 archetypes)', status: !!CHAMPION_VOICE_995.grinder },
    { name: 'Power Rankings Show (5 tiers)', status: !!POWER_RANKINGS_SHOW_995.rank1 },
    { name: 'Rivalry Trophies (16 names)', status: RIVALRY_TROPHIES_986.names.length === 16 },
    { name: 'Power Rankings Generator', status: typeof POWER_RANKINGS_986.generate === 'function' },
    { name: 'Cap Projections (3-year)', status: typeof CAP_PROJ_986.project === 'function' },
    { name: 'Generational Players', status: typeof GENERATIONAL_986.shouldSpawn === 'function' },
    { name: 'Owner Mode (tickets/stadium)', status: OWNER_MODE_986.ticketTiers.length === 4 },
    { name: 'Player Comparison Radar', status: typeof PLAYER_COMPARE_986.buildRadar === 'function' },
    { name: 'Franchise Timeline', status: typeof TIMELINE_986.addEvent === 'function' },
    { name: 'Retirement & HoF Ceremonies', status: typeof CEREMONY_986.generateRetirementSpeech === 'function' },
    { name: 'Practice Squad System', status: PRACTICE_SQUAD_986.MAX_SIZE === 16 },
    { name: 'Player Holdouts v2', status: HOLDOUT_V2_986.types.length === 3 },
    { name: 'Expansion Draft Event', status: EXPANSION_DRAFT_986.cities.length === 10 },
    { name: 'Scout Spending Menu (12 options)', status: SCOUT_SPEND_MENU95.length === 12 },
    { name: 'Scout Math (error bands)', status: typeof SCOUT_MATH.getErrorBand === 'function' },
    { name: 'Scout Note Flavor Text', status: typeof getScoutNoteFlavor === 'function' },
    { name: 'Unlock System (5 progressive)', status: UNLOCK_DEFS.length === 5 },
    { name: 'Tab Unlock Logic', status: typeof isTabUnlocked === 'function' },
    { name: 'LZW Compression', status: typeof LZW.compress === 'function' },
    { name: 'Keyboard Shortcuts', status: KEYMAP['1'] === 'home' },
    { name: 'Action Keys', status: ACTION_KEYS[' '] === 'simWeek' },
    { name: 'Tab Navigation Order', status: TAB_ORDER.length === 10 },
    { name: 'Special Plays (4 trick + 3 pass)', status: SPECIAL_PLAYS_993.trickPlays.length === 4 },
    { name: 'Special Coverages (4 packages)', status: SPECIAL_COVERAGES_993.length === 4 },
    { name: 'Expected Points Table (4 downs)', status: !!EP_TABLE_993[1] && !!EP_TABLE_993[4] },
    { name: 'Win Probability Engine v2', status: typeof calcWinProbV2_993 === 'function' },
    { name: 'Playbook (offense + defense)', status: !!PLAYBOOK_986.offense && !!PLAYBOOK_986.defense },
    { name: 'Press Conference System', status: PRESS_CONF_986.questions.length === 8 },
    { name: 'Legacy Score System', status: typeof LEGACY.calcScore === 'function' },
    { name: 'Relocation System (10 cities)', status: RELOCATION_CITIES976.length === 10 },
    { name: 'Coach Personalities (6 archetypes)', status: Object.keys(COACH_PERSONALITIES_991).length === 6 },
    { name: 'Broadcast Commentary (base)', status: !!BROADCAST_COMMENTARY.drives },
    { name: 'Broadcast Commentary (expanded)', status: !!BROADCAST_COMMENTARY_EXPANDED.drives },
    { name: 'MFSN Draft Commentary', status: MFSN_DRAFT_LINES.length >= 5 },
    { name: 'MFSN Show System', status: !!MFSN_SHOW },
    { name: 'MFSN Content Templates', status: !!MFSN_CONTENT_991 },
    { name: 'MFSN Weekly Show', status: !!MFSN_WEEKLY975 },
    { name: 'MFSN Broadcast Data', status: !!MFSN_BROADCAST },
    { name: 'MFSN Draft Grades', status: !!MFSN_DRAFT_GRADES },
    { name: 'MFSN Predictions', status: !!MFSN_PREDICTIONS },
    { name: 'MFSN Expanded (ST, injuries, crowd)', status: !!MFSN_EXPANDED_993.drives },
    { name: 'MFSN Situational Commentary', status: !!MFSN_SITUATIONAL_994.situational },
    { name: 'MFSN Fourth Down Analysis', status: !!MFSN_FOURTH_DOWN_994 },
    { name: 'MFSN Drive Summaries', status: !!MFSN_DRIVES_994 },
    { name: 'Social Media Feed', status: !!SOCIAL_FEED_994 },
    { name: 'MFSN Overtime Drama', status: !!MFSN_OVERTIME_994 },
    { name: 'GM Strategies (rebuild/contend/neutral)', status: !!GM_STRATEGIES.rebuild && !!GM_STRATEGIES.contend },
    { name: 'Front Office (7 roles, 15 traits)', status: FRONT_OFFICE.roles.length === 7 },
    { name: 'Story Arc Engine (state machine)', status: typeof STORY_ARC_ENGINE.tickPlayer === 'function' },
    { name: 'Weekly Challenges (10 pool)', status: WEEKLY_CHALLENGES.pool.length === 10 },
    { name: 'Trade Deadline Frenzy (AI trades)', status: typeof TRADE_DEADLINE_FRENZY.generateAITrades === 'function' },
    { name: 'Weather System (climate + impacts)', status: typeof WEATHER.getConditions === 'function' },
    { name: 'Halftime Conditions (5 states)', status: HT_CONDITIONS.length === 5 },
    { name: 'Halftime Strategies (6 options)', status: HT_STRATEGIES.length === 6 },
    { name: 'Player Archetypes (9 positions)', status: typeof PLAYER_ARCHETYPES.classify === 'function' },
    { name: 'Archetype Aging (30 curves)', status: Object.keys(ARCHETYPE_AGING.mods).length === 30 },
    { name: 'Age Curves (10 positions)', status: Object.keys(AGE_CURVES).length === 10 },
    { name: 'Coach Skill Tree (3 trees x 3 branches)', status: !!COACH_SKILL_TREE.trees.Strategist },
    { name: 'Owner Patience System', status: typeof OWNER_PATIENCE.tick === 'function' },
    { name: 'Owner Confidence Arc (4 stages)', status: OWNER_CONFIDENCE_ARC.stages.length === 4 },
    { name: 'Owner Consequences & Ultimatums', status: OWNER_CONSEQUENCES.ultimatums.length === 3 },
    { name: 'Trade Math (classify/trust/decay)', status: typeof TRADE_MATH.classify === 'function' },
    { name: 'Records Wall (13 categories)', status: RECORDS_WALL.categories.length === 13 },
    { name: 'GM Trade Pitch (6 personality types)', status: typeof getGMTradePitch === 'function' },
    { name: 'Player Names (4 pools x 11 pos)', status: !!PLAYER_NAMES_991.first.classic },
    { name: 'Breakout System (pick/resolve/milestone)', status: typeof BREAKOUT_SYSTEM.pick === 'function' },
    { name: 'Grudge Match (player revenge)', status: typeof GRUDGE_MATCH.applyBoost === 'function' },
    { name: 'Revenge Game (rivalry bonuses)', status: typeof REVENGE_GAME.check === 'function' },
    { name: 'Mentor System (7 pos groups)', status: Object.keys(MENTOR_SYSTEM.posGroups).length === 7 },
    { name: 'Staff Poaching (check/counter/apply)', status: typeof STAFF_POACHING.checkPoach === 'function' },
    { name: 'All-Time Records (12 categories)', status: ALL_TIME_RECORDS.categories.length === 12 },
    { name: 'Scouting Templates (9 positions)', status: Object.keys(SCOUTING_TEMPLATES_991).length === 9 },
    { name: 'Draft Commentary (round/OVR lines)', status: typeof getDraftCommentary === 'function' },
    { name: 'Draft Analyst (multi-personality)', status: !!DRAFT_ANALYST_993.rodPemberton },
    { name: 'Film Study (off/def/ST grading)', status: typeof FILM.analyze === 'function' },
    { name: 'Agent Types (5 FA personalities)', status: AGENT_TYPES.length === 5 },
    { name: 'Agent Type Assignment', status: typeof assignAgentType === 'function' },
    { name: 'Trust Trend Indicators', status: typeof TRUST_TREND.getArrow === 'function' },
    { name: 'Aging v2 (physical/mental/technique)', status: typeof AGING_V2.getMultiplier === 'function' },
    { name: 'GM Trust Snapshot', status: typeof TRUST.leagueSnapshot === 'function' },
    { name: 'Holdout System (5 stages)', status: typeof HOLDOUT_SYSTEM.checkHoldouts === 'function' },
    { name: 'Position Market Tiers', status: typeof getPosMarketTier86 === 'function' },
    { name: 'Fatigue Multiplier (snap-based)', status: typeof calcFatigueMultiplier === 'function' },
    { name: 'Game Script Multiplier', status: typeof calcGameScriptMult === 'function' },
    { name: 'Week-over-Week Deltas', status: typeof calcWeekDeltas === 'function' },
    { name: 'Performance Attribution Engine', status: typeof attributeCause === 'function' },
    { name: 'Award History Tracking', status: Array.isArray(AWARD_HISTORY_LOG) },
    { name: 'Multi-Time Award Winners', status: typeof getMultiTimeWinners === 'function' },
    { name: 'Rivalry Trophy Names', status: typeof getTrophyName === 'function' },
    { name: 'Player Career Pages', status: typeof buildCareerPage === 'function' },
    { name: 'Coach Legacy Tracking', status: typeof updateCoachLegacy === 'function' },
    { name: 'Coach Ring Records', status: typeof recordCoachRing === 'function' },
    { name: 'DNA Impact Reports', status: typeof buildDNAImpactReport === 'function' },
    { name: 'Trade Value Calculator (simple)', status: typeof calcTradeValue === 'function' },
    { name: 'Pick Value Chart (simple)', status: calcPickValue(1) === 80 },
    { name: 'Trade Package Evaluator', status: typeof evaluateTradePackage === 'function' },
    { name: 'Ring of Honor System', status: typeof nominateForRing === 'function' },
    { name: 'Ring of Honor (auto-nom)', status: typeof autoRingOfHonor === 'function' },
    { name: 'Owner Personality Events (10)', status: OWNER_PERSONALITY_EVENTS.length === 10 },
    { name: 'Owner Personality Checker', status: typeof checkOwnerPersonality === 'function' },
    { name: 'Awards Ceremony Builder', status: typeof buildAwardsCeremony === 'function' },
    { name: 'Cap Visualization (breakdown)', status: typeof buildCapVisualization === 'function' },
    { name: 'Role Definitions (RB/WR/DL/LB)', status: !!ROLE_DEFS.RB && ROLE_DEFS.RB.length === 3 },
    { name: 'Role Assignment & Snap %', status: typeof assignDefaultRoles === 'function' && typeof getRoleSnapPct === 'function' },
    { name: 'Dominance Score Calculator', status: typeof calcDominanceScore === 'function' },
    { name: 'Dynasty Index (multi-factor)', status: typeof calcDynastyIndex === 'function' },
    { name: 'Peak Power Window (5-year)', status: typeof calcPeakPower === 'function' },
    { name: 'Longevity Tracker', status: typeof calcLongevity === 'function' },
    { name: 'Identity Tags (up to 3)', status: typeof generateIdentityTags === 'function' },
    { name: 'Era Card Generator', status: typeof generateEraCards === 'function' },
    { name: 'Hall of Seasons (top 20)', status: typeof buildHallOfSeasons === 'function' },
    { name: 'Rivalry Key & Hate Week', status: typeof rivalryKey === 'function' && typeof checkHateWeek === 'function' },
    { name: 'Rivalry Moments (5 gravity levels)', status: Object.keys(MOMENT_GRAVITY).length === 5 },
    { name: 'Rivalry Trophy Case', status: typeof buildRivalryTrophyCase === 'function' },
    { name: 'Rivalry Ladder (full + lite)', status: typeof buildRivalryLadder === 'function' && typeof buildRivalryLadderLite === 'function' },
    { name: 'Game Highlights & Receipts', status: typeof generateHighlights === 'function' && typeof generateReceipts === 'function' },
    { name: 'Fix-It Drills (9 types)', status: Object.keys(FIX_IT_DRILLS).length === 9 },
    { name: 'Rivalry Trash Talk (3 tiers)', status: !!RIVALRY_TRASH_991.mild && !!RIVALRY_TRASH_991.spicy && !!RIVALRY_TRASH_991.atomic },
    { name: 'College Pipeline (Power 50)', status: COL_POWER.length === 50 },
    { name: 'College Pipeline (G5 29)', status: COL_G5.length === 29 },
    { name: 'College Pipeline (FCS 9)', status: COL_FCS.length === 9 },
    { name: 'College Weighted Pool', status: COL_WEIGHTED.length > 50 },
    { name: 'Pick College Function', status: typeof pickCollege === 'function' },
    { name: 'Broadcast Voices (3 announcers)', status: BROADCAST_VOICES_991.voices.length === 3 },
    { name: 'Broadcast Voice Calls', status: typeof BROADCAST_VOICES_991.getCall === 'function' },
    { name: 'Practice Focus (4 options)', status: PRACTICE_FOCUS.length === 4 },
    { name: 'Captain Rules (system)', status: CAPTAIN_RULES.eligibleMinOvr === 70 },
    { name: 'Captain Moment Types (3)', status: CAPTAIN_MOMENT_TYPES.length === 3 },
    { name: 'Prospect Claims (generate)', status: typeof PROSPECT_CLAIMS.generate === 'function' },
    { name: 'Prospect Claims (verify)', status: typeof PROSPECT_CLAIMS.verify === 'function' },
    { name: 'Coaching Clinic Tracks (5)', status: CLINIC_TRACKS.length === 5 },
    { name: 'Coaching Clinic (earnXP)', status: typeof CLINIC.earnXP === 'function' },
    { name: 'Coaching Clinic Math (getMods)', status: typeof CLINIC_MATH.getMods === 'function' },
    { name: 'Media Tags (6 archetypes)', status: Object.keys(MEDIA_TAGS).length === 6 },
    { name: 'Press Tag Map (18 mappings)', status: Object.keys(PRESS_TAG_MAP).length >= 17 },
    { name: 'Media Persona Detection', status: typeof getMediaPersona === 'function' },
    { name: 'Credibility Math (calcDelta)', status: typeof CREDIBILITY_MATH.calcDelta === 'function' },
    { name: 'Rivalry Math (calcDelta)', status: typeof RIVALRY_MATH.calcDelta === 'function' },
    { name: 'Press Questions (5 scenarios)', status: PRESS_QUESTIONS.length === 5 },
    { name: 'Headlines Generator', status: typeof HEADLINES.generate === 'function' },
    { name: 'Hall of Fame Log (array)', status: Array.isArray(HALL_OF_FAME_LOG) },
    { name: 'HOF Speeches (6 traits)', status: Object.keys(HOF_SPEECHES).length === 6 },
    { name: 'HOF Speech Getter', status: typeof getHOFSpeech === 'function' },
    { name: 'Legacy Score Calculator', status: typeof calcLegacyScore === 'function' },
    { name: 'Auto Hall of Fame', status: typeof autoHallOfFame === 'function' },
    { name: 'Cap Fixes Builder', status: typeof buildCapFixes === 'function' },
    { name: 'Scout Perception (gaussian)', status: typeof SCOUT.gaussian === 'function' },
    { name: 'Scout Perceived Rating', status: typeof SCOUT.getPerceived === 'function' },
    { name: 'Scout Range Calculator', status: typeof SCOUT.getRange === 'function' },
    { name: 'Scout Grade Range', status: typeof SCOUT.getGradeRange === 'function' },
    { name: 'OC Specialties (5 types)', status: OC_SPECIALTIES.length === 5 },
    { name: 'DC Specialties (5 types)', status: DC_SPECIALTIES.length === 5 },
    { name: 'Coordinator Assignment', status: typeof assignCoordSpecialty === 'function' },
    { name: 'Prospect Character (10 types)', status: PROSPECT_CHARACTER.types.length === 10 },
    { name: 'Prospect Character Assignment', status: typeof PROSPECT_CHARACTER.assign === 'function' },
    { name: 'Bust/Steal Calculator', status: typeof BUST_STEAL_CALC.calc === 'function' },
    { name: 'Draft Day Trade-Up Logic', status: typeof DRAFT_DAY_TRADES.shouldTradeUp === 'function' },
    { name: 'Draft Day AI Offers', status: typeof DRAFT_DAY_TRADES.makeOffer === 'function' },
    { name: 'Draft Eval (safety compare)', status: typeof DRAFT_EVAL.compareSafety === 'function' },
    { name: 'Injury Report Generator', status: typeof INJURY_REPORT.generate === 'function' },
    { name: 'Playoff Bracket Tree', status: typeof buildBracketTree === 'function' },
    { name: 'Draft Presser (questions)', status: typeof DRAFT_PRESSER975.generateQuestions === 'function' },
    { name: 'Dossier (getEntry)', status: typeof DOSSIER.getEntry === 'function' },
    { name: 'Dossier (scout)', status: typeof DOSSIER.scout === 'function' },
    { name: 'Dossier (decay)', status: typeof DOSSIER.decay === 'function' },
    { name: 'Dossier (verify)', status: typeof DOSSIER.verify === 'function' },
    { name: 'Scout Report Generator', status: typeof SCOUT_REPORT.generate === 'function' },
    { name: 'Prospect Dossier (getEntry)', status: typeof PROSPECT_DOSSIER.getEntry === 'function' },
    { name: 'Prospect Dossier (scout)', status: typeof PROSPECT_DOSSIER.scout === 'function' },
    { name: 'Prospect Dossier (decay)', status: typeof PROSPECT_DOSSIER.decay === 'function' },
    { name: 'Prospect Dossier (verify)', status: typeof PROSPECT_DOSSIER.verify === 'function' },
    { name: 'Draft War Room (getIntel)', status: typeof DRAFT_WAR_ROOM.getIntel === 'function' },
    { name: 'Draft War Room (schemeFit)', status: typeof DRAFT_WAR_ROOM.schemeFitScore === 'function' },
    { name: 'Offseason Events (8 templates)', status: OFFSEASON_EVENTS.templates.length === 8 },
    { name: 'Offseason Events Generator', status: typeof OFFSEASON_EVENTS.generate === 'function' },
    { name: 'Owner Goal Templates (7)', status: OWNER_GOAL_TEMPLATES.length === 7 },
    { name: 'Coach Goal Templates (5)', status: COACH_GOAL_TEMPLATES.length === 5 },
    { name: 'Player Goal Templates (11)', status: PLAYER_GOAL_TEMPLATES.length === 11 },
    { name: 'Season Goals Generator', status: typeof generateSeasonGoals === 'function' },
    { name: 'Player Goals Generator', status: typeof generatePlayerGoals === 'function' },
    { name: 'Goal Progress Updater', status: typeof updateGoalProgress === 'function' },
    { name: 'Goals Evaluator', status: typeof evaluateGoals === 'function' },
    { name: 'Help Sections (3 groups)', status: HELP_SECTIONS.length === 3 },
    { name: 'Skin Tones (7 values)', status: SKIN_TONES.length === 7 },
    { name: 'Hair Colors (7 values)', status: HAIR_COLORS.length === 7 },
    { name: 'Locker Events (18 events)', status: LOCKER_EVENTS.length === 18 },
    { name: 'Locker Events Checker', status: typeof checkLockerEvents === 'function' },
    { name: 'Coach Trait Mods', status: typeof getCoachTraitMods === 'function' },
    { name: 'Owner Types (3)', status: OWNER_TYPES.length === 3 },
    { name: 'Owner Goals (9)', status: OWNER_GOALS.length === 9 },
    { name: 'Stat Headlines (13)', status: STAT_HEADLINES.length === 13 },
    { name: 'Stat Headline Getter', status: typeof getStatHeadline === 'function' },
    { name: 'Trait Morale Explainer', status: typeof getTraitMoraleExplainer === 'function' },
    { name: 'Story Templates (15)', status: STORY_TEMPLATES.length === 15 },
    { name: 'Presser Tag Triggers (6)', status: PRESSER_TAG_TRIGGERS.length === 6 },
    { name: 'Grade Letter Function', status: typeof gradeL === 'function' },
    { name: 'Fuzzy Rating Display', status: typeof getFuzzyRating === 'function' },
    { name: 'Fuzzy Grade Display', status: typeof getFuzzyGrade === 'function' },
    { name: 'Offseason News (8 templates)', status: OFFSEASON_NEWS.templates.length === 8 },
    { name: 'Offseason News Generator', status: typeof OFFSEASON_NEWS.generate === 'function' },
    { name: 'FA Narrative (7 categories)', status: Object.keys(FA_NARRATIVE_993).length === 7 },
    { name: 'FA Narrative (bigSigning)', status: FA_NARRATIVE_993.bigSigning.length >= 20 },
    { name: 'Press Conference Expanded (questions)', status: Object.keys(PRESS_CONFERENCE_993.questions).length === 13 },
    { name: 'Press Conference Expanded (answers)', status: Object.keys(PRESS_CONFERENCE_993.answers).length === 13 },
    { name: 'Press Conference Expanded (reactions)', status: PRESS_CONFERENCE_993.mediaReaction.length >= 15 },
    // Phase 1u: Game sim math, AI gameplan, rivalry game day
    { name: 'getRivalryLabel function', status: typeof getRivalryLabel === 'function' },
    { name: 'findRivalObj function', status: typeof findRivalObj === 'function' },
    { name: 'WP_TABLE_DEEPSEEK (28 entries)', status: Object.keys(WP_TABLE_DEEPSEEK).length === 28 },
    { name: 'momentumDecay991 function', status: typeof momentumDecay991 === 'function' },
    { name: 'edgeToProbability991 function', status: typeof edgeToProbability991 === 'function' },
    { name: 'draftPickOvr991 function', status: typeof draftPickOvr991 === 'function' },
    { name: 'aiPickOffGPPreview function', status: typeof aiPickOffGPPreview === 'function' },
    { name: 'aiPickDefGPPreview function', status: typeof aiPickDefGPPreview === 'function' },
    { name: 'RIVALRY_TROPHIES977 (8 templates)', status: RIVALRY_TROPHIES977.templates.length === 8 },
    { name: 'RIVALRY_TROPHIES977.generateTrophy', status: typeof RIVALRY_TROPHIES977.generateTrophy === 'function' },
    { name: 'RIVALRY_TROPHIES977.updateTrophy', status: typeof RIVALRY_TROPHIES977.updateTrophy === 'function' },
    { name: 'RIVALRY_WEEK977.getAtmosphere', status: typeof RIVALRY_WEEK977.getAtmosphere === 'function' },
    { name: 'PREGAME_TALK977.generate', status: typeof PREGAME_TALK977.generate === 'function' },
    { name: 'HALFTIME_PANEL977.generate', status: typeof HALFTIME_PANEL977.generate === 'function' },
    { name: 'POSTGAME_LOCKER977.generate', status: typeof POSTGAME_LOCKER977.generate === 'function' },
    { name: 'GAME_OF_WEEK977.pick', status: typeof GAME_OF_WEEK977.pick === 'function' },
    { name: 'buildRivalryDashboard977 function', status: typeof buildRivalryDashboard977 === 'function' },
    // Phase 1v: FA config, DB cleaner, roster mgmt, negotiation, arc spotlight
    { name: 'FA_TIERS (4 tiers)', status: Object.keys(FA_TIERS).length === 4 },
    { name: 'getFATier function', status: typeof getFATier === 'function' },
    { name: 'FA_PHASES (3 phases)', status: Object.keys(FA_PHASES).length === 3 },
    { name: 'FA_ROLE_PITCH (4 roles)', status: Object.keys(FA_ROLE_PITCH).length === 4 },
    { name: 'RFA_TENDERS (3 tenders)', status: Object.keys(RFA_TENDERS).length === 3 },
    { name: 'FA_MARKET_VALUE.calc', status: typeof FA_MARKET_VALUE.calc === 'function' },
    { name: 'FA_PRIORITY_TAGS (6 tags)', status: FA_PRIORITY_TAGS.length === 6 },
    { name: 'DB_CLEANER.findStale', status: typeof DB_CLEANER.findStale === 'function' },
    { name: 'DB_CLEANER.prune', status: typeof DB_CLEANER.prune === 'function' },
    { name: 'detectPositionBattles974 function', status: typeof detectPositionBattles974 === 'function' },
    { name: 'buildCutAdvisor974 function', status: typeof buildCutAdvisor974 === 'function' },
    { name: 'NEGOTIATION_SCENE.getOpeningLine', status: typeof NEGOTIATION_SCENE.getOpeningLine === 'function' },
    { name: 'NEGOTIATION_SCENE.getCounterLine', status: typeof NEGOTIATION_SCENE.getCounterLine === 'function' },
    { name: 'ARC_SPOTLIGHT (8 arc types)', status: Object.keys(ARC_SPOTLIGHT.lines).length === 8 },
    { name: 'ARC_SPOTLIGHT.generate', status: typeof ARC_SPOTLIGHT.generate === 'function' },
  ];
}

export function isValidStatusRowShape(row) {
  return !!row &&
    typeof row.name === 'string' &&
    row.name.length > 0 &&
    typeof row.status === 'boolean';
}
